networks:
  internal:
  alwatr-public-network:
    name: alwatr-public-network
    external: true

services:
  app:
    image: $appImage

    cpu_count: 1
    cpu_shares: 1024
    mem_limit: 256m

    restart: unless-stopped

    networks:
      alwatr-public-network:

    environment:
      - NGINX_ACCESS_LOG=${appAccessLog:-}
      - NGINX_FORCE_DOMAIN=${nginxForceDomain:-}

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'

    labels:
      traefik.enable: true
      traefik.port: 80
      traefik.frontend.rule: Host:${domain}; PathPrefix:/;
      traefik.frontend.entryPoints: http, https
      traefik.frontend.redirect.entryPoint: https

  api:
    image: $apiImage

    cpu_count: 1
    cpu_shares: 1024
    mem_limit: 256m

    restart: unless-stopped

    networks:
      internal:
      alwatr-public-network:

    depends_on:
      - storage-api

    environment:
      - STORAGE_HOST=${appId}-storage-api
      - STORAGE_PORT=80
      - STORAGE_TOKEN=${storageAccessToken}
      - ALWATR_DEBUG=${apiDebug:-}

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'

    labels:
      traefik.enable: true
      traefik.port: 80
      traefik.frontend.rule: Host:${domain}; PathPrefix:/api/v1/;
      traefik.frontend.entryPoints: http, https
      traefik.frontend.redirect.entryPoint: https

  storage-api:
    image: ghcr.io/alwatr/storage-api:4.0.2

    cpu_count: 1
    cpu_shares: 1024
    mem_limit: 256m

    stop_grace_period: 30s

    restart: unless-stopped

    networks:
      internal:
        aliases:
          - '${appId}-storage-api'

    environment:
      - STORAGE_PATH=/data
      - ACCESS_TOKEN=${storageAccessToken}
      - ALWATR_DEBUG=${storageApiDebug:-}

    volumes:
      - type: bind
        source: ./_data/storage
        target: /data
        bind:
          create_host_path: true

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'

  nginx-storage:
    image: ghcr.io/alwatr/nginx-storage:4.0.2

    cpu_count: 1
    cpu_shares: 1024
    mem_limit: 256m

    restart: unless-stopped

    networks:
      alwatr-public-network:

    environment:
      - NGINX_ACCESS_LOG=${storageAccessLog:-off}

    volumes:
      - type: bind
        source: ./_data/storage
        target: /data
        bind:
          create_host_path: true

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'

    labels:
      traefik.enable: true
      traefik.port: 80
      traefik.frontend.rule: Host:${domain}; PathPrefixStrip:/api/v1/publistore/
      traefik.frontend.entryPoints: http, https
      traefik.frontend.redirect.entryPoint: https
